namespace: helm-demo
image:
  repository: nginx
  tag: latest
service:
  type: LoadBalancer
securityContext:
  enabled: true
  automountServiceAccountToken: false
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
resources:
  enabled: true
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
probes:
  enabled: true
